name: Up To Date w/ Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Up To Date
        run: |
          if ! git merge-base --is-ancestor origin/main ${{ github.event.pull_request.head.sha }};
          then echo "This branch is not up to date with main";
          exit 1; fi
